sudo: required

services:
  - docker

arch:
  packages:
    - ninja
    - meson

  script:
    - cd $SRCDIR
    - meson builddir
    - ninja -C builddir

language: cpp

env:
  - SRCDIR=c
  - SRCDIR=cpp
  - SRCDIR=bash

compiler:
  - gcc
  - clang

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
