sudo: required

services:
  - docker

archlinux:
  packages:
    - ninja
    - meson

  script:
    - cd $SRCDIR
    - "[[ -f meson.build ]] && meson builddir"
    - "[[ -f meson.build ]] && ninja -C builddir"
    - "[[ -f Makefile ]] && make"

language: cpp

env:
  - SRCDIR=c
  - SRCDIR=cpp
  - SRCDIR=bash

compiler:
  - gcc
  - clang

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
