sudo: required

services:
  - docker

archlinux:
  packages:
    - ninja
    - meson

  script:
    - cd $SRCDIR
    - "if [[ -f meson.build ]]; then meson builddir -Ddefault_library=both && ninja -C builddir && tests/run_tests.sh; fi"
    - "if [[ -f Makefile ]]; then make check; fi"

language: cpp

env:
  - SRCDIR=c
  - SRCDIR=cpp
  - SRCDIR=bash

compiler:
  - gcc
  - clang

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
